{% set name = "rocksdbdict" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dabb63c7177ee397dd19fba1fa8bab9e75eb40baaf8312286d38e1ceb4f9acf1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - python-rocksdb >=0.7.0

test:
  imports:
    - rocksdbdict
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/adammarples/rocksdbdict
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A wrapper for python-rocksdb with a dict-like interface
  description: |
    A wrapper for python-rocksdb with a dict-like interface.
  doc_url: https://github.com/adammarples/rocksdbdict
  dev_url: https://github.com/adammarples/rocksdbdict

extra:
  recipe-maintainers:
    - acamargo
